#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

$OPENSHIFT_REPO_DIR/gradlew build
nohup java -jar $OPENSHIFT_REPO_DIR/build/libs/springseed-devbuild.jar
--server.port=8080 > OPENSHIFT_REPO_DIR/openshift.log &
