#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

nohup java -jar $OPENSHIFT_REPO_DIR/diy/springseed-devbuild.jar --server.address=$OPENSHIFT_DIY_IP --server.port=8080 |& /usr/bin/logshifter -tag diy &
